name: audioplayers_web
description: Web implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 4.1.0
publish_to: none
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AudioplayersPlugin
        fileName: audioplayers_web.dart

dependencies:
  audioplayers_platform_interface:
    git: https://github.com/kumsumit/audioplayers_platform_interface.git
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
